import { expect, test } from '@playwright/test'
import { addBoardCard, column, openBoard, openBoardCard } from './support/board-fixtures'

test('creates title-only cards, saves plain text details and real comments, reloads and confirms deletion', async ({ page }) => {
  await openBoard(page)
  await expect(page.locator('.kanban-column h2')).toHaveText(['Backlog', 'Todo', 'In Progress', 'Review', 'Done', 'Closed'])
  await expect(column(page, 'Backlog')).toHaveCSS('width', '272px')
  await expect(column(page, 'Backlog')).toHaveCSS('background-color', 'rgb(241, 242, 244)')
  await expect(page.locator('.kanban-lists')).toHaveCSS('gap', '12px')
  await addBoardCard(page, 'Write the plan')
  await expect(page.locator('.kanban-card')).toHaveText('Write the plan')
  await expect(page.locator('.kanban-card > *')).toHaveCount(0)
  await openBoardCard(page, 'Write the plan')
  const modal = page.getByRole('dialog')
  await modal.getByLabel('Title', { exact: true }).fill('Plan launch')
  await modal.getByLabel('Description', { exact: true }).fill('<b>Plain text only</b>\nSecond line')
  await expect(modal.getByRole('combobox')).toHaveCount(0)
  await expect(modal.getByText('Move card', { exact: true })).toHaveCount(0)
  await modal.getByLabel('New comment').fill('A real discussion')
  await modal.getByRole('button', { name: 'Add comment' }).click()
  await expect(modal.getByText('A real discussion', { exact: true })).toBeVisible()
  await expect(modal.locator('.kanban-comments strong')).not.toBeEmpty()
  await expect(modal.locator('time')).toHaveAttribute('datetime', /\d{4}-\d{2}-\d{2}T/)
  await expect(modal.getByLabel('Description')).toHaveValue('<b>Plain text only</b>\nSecond line')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(modal).toHaveCount(0)
  await expect(column(page, 'Backlog').locator('.kanban-card')).toHaveText('Plan launch')
  await column(page, 'Backlog').locator('.kanban-card').dragTo(column(page, 'Todo'))
  await expect(column(page, 'Todo').locator('.kanban-card')).toHaveText('Plan launch')
  await page.reload()
  await page.getByRole('tab', { name: 'Board', exact: true }).click()
  await openBoardCard(page, 'Plan launch')
  await expect(modal.getByLabel('Description')).toHaveValue('<b>Plain text only</b>\nSecond line')
  await expect(modal.getByText('A real discussion', { exact: true })).toBeVisible()
  page.once('dialog', (dialog) => dialog.dismiss())
  await modal.getByRole('button', { name: 'Delete card' }).click()
  await expect(modal).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await modal.getByRole('button', { name: 'Delete card' }).click()
  await expect(modal).toHaveCount(0)
  await expect(page.locator('.kanban-card')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('lean-canvas:boards:v1')!))
    .every((board) => (board as { comments: unknown[] }).comments.length === 0))).toBe(true)
  await page.getByRole('tab', { name: 'Canvas', exact: true }).click()
  await expect(page.getByText('Decisions disappear across chat, docs, and meetings')).toBeVisible()
})

test('protects dirty title, description and comment drafts on Escape, Cancel and reload; restores focus', async ({ page }) => {
  await openBoard(page)
  await addBoardCard(page, 'Draft card')
  await openBoardCard(page, 'Draft card')
  const modal = page.getByRole('dialog')
  await modal.getByLabel('Description').fill('Uncommitted')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.keyboard.press('Escape')
  await expect(modal.getByLabel('Description')).toHaveValue('Uncommitted')
  // Native showModal makes navigation behind the draft inert, including touch and keyboard.
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).not.toBeFocused()
  await modal.getByRole('button', { name: 'Close dialog' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).not.toBeFocused()
  await page.keyboard.press('Tab')
  await expect(modal.getByRole('button', { name: 'Close dialog' })).toBeFocused()
  page.once('dialog', (dialog) => dialog.accept())
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Draft card', exact: true })).toBeFocused()
  await openBoardCard(page, 'Draft card')
  await expect(modal.getByLabel('Description')).toHaveValue('')
  await modal.getByLabel('New comment').fill('Not sent')
  const reloadPrompt = page.waitForEvent('dialog')
  await page.evaluate(() => { window.setTimeout(() => window.location.reload(), 0) })
  const prompt = await reloadPrompt
  expect(prompt.type()).toBe('beforeunload')
  await prompt.dismiss()
  await expect(modal.getByLabel('New comment')).toHaveValue('Not sent')
  page.once('dialog', (dialog) => dialog.accept())
  await page.keyboard.press('Escape')
  await expect(modal).toHaveCount(0)
  await page.getByRole('tab', { name: 'Board', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).toHaveAttribute('aria-selected', 'true')
})
