import { expect, test } from '@playwright/test'
import { addBoardCard, column, openBoard, openBoardCard } from './support/board-fixtures'

for (const fallback of [false, true]) {
  test(`column action panel floats without reflow, dismisses and restores focus${fallback ? ' without Popover API' : ''}`, async ({ page }) => {
    if (fallback) await page.addInitScript(() => { delete (HTMLElement.prototype as { popover?: string }).popover })
    await page.setViewportSize({ width: 1200, height: 710 })
    await openBoard(page)
    const list = column(page, 'Backlog')
    const trigger = list.getByRole('button', { name: 'Column actions for Backlog' })
    const before = await list.boundingBox()
    const headingBefore = await list.getByRole('heading').boundingBox()
    await trigger.click()
    const panel = page.getByRole('group', { name: 'Column actions for Backlog' })
    await expect(panel).toBeVisible()
    expect(await list.boundingBox()).toEqual(before)
    expect(await list.getByRole('heading').boundingBox()).toEqual(headingBefore)
    await expect(panel.getByRole('button', { name: 'Rename column' })).toBeFocused()
    const box = (await panel.boundingBox())!
    expect(box.y + box.height).toBeGreaterThan(before!.y + before!.height)
    expect(box.x).toBeGreaterThanOrEqual(8)
    expect(box.x + box.width).toBeLessThanOrEqual(1192)
    await page.keyboard.press('Escape')
    await expect(panel).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.locator('.kanban-lists').click({ position: { x: 400, y: 350 } })
    await expect(panel).toHaveCount(0)
    await trigger.click()
    await panel.getByRole('button', { name: 'Rename column' }).click()
    await expect(panel).toHaveCount(0)
    await expect(page.getByRole('dialog').getByLabel('Title')).toBeFocused()
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click()
    await expect(trigger).toBeFocused()
    // A far-right empty column still opens an actionable panel within a narrow viewport.
    await page.setViewportSize({ width: 390, height: 710 })
    const last = column(page, 'Closed').getByRole('button', { name: 'Column actions for Closed' })
    await last.scrollIntoViewIfNeeded()
    await last.click()
    const narrowPanel = page.getByRole('group', { name: 'Column actions for Closed' })
    const narrowBox = (await narrowPanel.boundingBox())!
    expect(narrowBox.x).toBeGreaterThanOrEqual(8)
    expect(narrowBox.x + narrowBox.width).toBeLessThanOrEqual(382)
    expect(narrowBox.y + narrowBox.height).toBeLessThanOrEqual(702)
    await narrowPanel.getByRole('button', { name: 'Move column left' }).click()
    await expect(narrowPanel).toHaveCount(0)
    await expect(last).toBeFocused()
  })
}

test('card details fits a short desktop viewport and stacks on mobile without nested forms or overflow', async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 710 })
  await openBoard(page)
  await addBoardCard(page, 'A focused card')
  await openBoardCard(page, 'A focused card')
  const modal = page.getByRole('dialog')
  const editor = modal.locator('.kanban-card-editor')
  const comments = modal.getByRole('region', { name: 'Comments' })
  const editorBox = (await editor.boundingBox())!
  const commentsBox = (await comments.boundingBox())!
  expect(commentsBox.x).toBeGreaterThan(editorBox.x + editorBox.width)
  expect(commentsBox.y).toBe(editorBox.y)
  const modalBox = (await modal.boundingBox())!
  expect(modalBox.width).toBeGreaterThanOrEqual(880)
  expect(modalBox.y + modalBox.height).toBeLessThanOrEqual(710)
  await expect(modal.getByRole('button', { name: 'Save', exact: true })).toBeInViewport()
  await expect(modal.getByRole('button', { name: 'Add comment' })).toBeInViewport()
  await expect(modal.getByRole('button', { name: 'Delete card' })).toBeInViewport()
  await expect(modal.locator('form')).toHaveCount(2)
  await expect(modal.locator('form form')).toHaveCount(0)
  expect(await modal.evaluate((element) => element.scrollHeight <= element.clientHeight)).toBe(true)
  await modal.getByLabel('Description').fill('A draft survives the responsive layout change.')
  await page.setViewportSize({ width: 390, height: 710 })
  await expect(modal.getByLabel('Description')).toHaveValue('A draft survives the responsive layout change.')
  const mobileEditor = (await editor.boundingBox())!
  const mobileComments = (await comments.boundingBox())!
  expect(mobileComments.y).toBeGreaterThan(mobileEditor.y + mobileEditor.height)
  expect(await modal.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await modal.getByLabel('New comment').fill('Readable on a small screen')
  await modal.getByRole('button', { name: 'Add comment' }).click()
  await expect(modal.getByText('Readable on a small screen', { exact: true })).toBeVisible()
})

test('mobile title wraps, retains initial focus and submits with Enter, including fixed-size fallback', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 710 })
  await openBoard(page)
  await addBoardCard(page, 'Validate the host onboarding flow')
  await expect(column(page, 'Backlog').getByLabel('1 card', { exact: true })).toBeVisible()
  await openBoardCard(page, 'Validate the host onboarding flow')
  const title = page.getByRole('dialog').getByLabel('Title', { exact: true })
  await expect(title).toBeFocused()
  expect(await title.evaluate((element) => element.scrollHeight <= element.clientHeight)).toBe(true)
  await page.addStyleTag({ content: '.kanban-title-field textarea { field-sizing: fixed !important; }' })
  expect(await title.evaluate((element) => element.scrollHeight <= element.clientHeight)).toBe(true)
  await title.fill('Validate the onboarding flow')
  await title.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.kanban-card')).toHaveText('Validate the onboarding flow')
  await expect(page.locator('.kanban-card > *')).toHaveCount(0)
})
