import { expect, test } from '@playwright/test'
import { addBoardCard, column, openBoard, openBoardCard } from './support/board-fixtures'

test('estimates persist on cards and in details after reload and movement, and can be cleared', async ({ page }) => {
  await openBoard(page)
  await addBoardCard(page, 'Add image upload')
  await openBoardCard(page, 'Add image upload')
  const modal = page.getByRole('dialog', { name: 'Card details' })
  const points = modal.getByRole('combobox', { name: 'Story points' })
  await expect(points).toHaveValue('')
  await expect(points.locator('option')).toHaveText(['Not estimated', '1 point', '3 points', '5 points', '8 points', '13+ points'])
  for (const [value, guidance] of [['1', 'Tiny, clear change'], ['3', 'Small standard task'], ['5', 'Moderate complexity'], ['8', 'Complex or risky'], ['13', 'split it']]) {
    await points.selectOption(value)
    await expect(points).toHaveAccessibleDescription(new RegExp(guidance))
  }
  await points.selectOption('5')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  const card = page.getByRole('button', { name: 'Add image upload 5 story points', exact: true })
  await expect(card).toBeVisible()
  await card.dragTo(column(page, 'Todo'))
  await expect(column(page, 'Todo').locator('.kanban-story-points-badge')).toHaveText('5 pts')
  await page.reload()
  await card.click()
  await expect(points).toHaveValue('5')
  await points.selectOption('13')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Add image upload 13+ story points', exact: true }).click()
  await expect(points).toHaveValue('13')
  await points.selectOption('')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.kanban-story-points-badge')).toHaveCount(0)
  await page.reload()
  await openBoardCard(page, 'Add image upload')
  await expect(points).toHaveValue('')
})

test('point-only drafts are keyboard accessible and protected by discard confirmation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openBoard(page)
  await addBoardCard(page, 'Change button text')
  await openBoardCard(page, 'Change button text')
  const modal = page.getByRole('dialog')
  const points = modal.getByRole('combobox', { name: 'Story points' })
  await expect(modal.getByRole('textbox', { name: 'Title', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(points).toBeFocused()
  await points.selectOption('1')
  await expect(points).toHaveValue('1')
  page.once('dialog', (dialog) => dialog.dismiss())
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(points).toHaveValue('1')
  page.once('dialog', (dialog) => dialog.accept())
  await page.keyboard.press('Escape')
  await openBoardCard(page, 'Change button text')
  await expect(points).toHaveValue('')
  const bounds = await points.boundingBox()
  expect(bounds!.width).toBeGreaterThan(100)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  await points.selectOption('1')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Change button text 1 story point', exact: true })).toBeVisible()
})
