import { expect, test } from '@playwright/test'
import { addBoardCard, column, openBoard } from './support/board-fixtures'

test('creates, renames, reorders and deletes only empty columns, isolated per canvas', async ({ page }) => {
  await openBoard(page)
  await addBoardCard(page, 'Keep this card')
  await column(page, 'Backlog').getByLabel('Column actions for Backlog').click()
  await expect(page.getByRole('group', { name: 'Column actions for Backlog' }).getByRole('button', { name: 'Delete column' })).toBeDisabled()
  await column(page, 'Backlog').getByLabel('Column actions for Backlog').click()
  await page.getByRole('button', { name: '+ Add another column', exact: true }).click()
  await page.getByLabel('Column title').fill('Custom work')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Add column', exact: true }).click()
  await expect(column(page, 'Custom work')).toBeVisible()
  await column(page, 'Custom work').getByLabel('Column actions for Custom work').click()
  await page.getByRole('group', { name: 'Column actions for Custom work' }).getByRole('button', { name: 'Move column left' }).click()
  await expect(page.locator('.kanban-column h2')).toHaveText(['Backlog', 'Todo', 'In Progress', 'Review', 'Done', 'Custom work', 'Closed'])
  await column(page, 'Custom work').getByRole('button', { name: 'Column actions for Custom work' }).click()
  await page.getByRole('group', { name: 'Column actions for Custom work' }).getByRole('button', { name: 'Rename column' }).click()
  await page.getByRole('dialog').getByLabel('Title').fill('Ready')
  await page.getByRole('dialog').getByRole('button', { name: 'Save' }).click()
  await expect(column(page, 'Ready')).toBeVisible()
  await page.reload()
  await page.getByRole('tab', { name: 'Board', exact: true }).click()
  await expect(page.locator('.kanban-column h2')).toHaveText(['Backlog', 'Todo', 'In Progress', 'Review', 'Done', 'Ready', 'Closed'])
  await page.getByRole('button', { name: 'Add canvas' }).click()
  await page.getByRole('button', { name: 'New', exact: true }).click()
  await page.getByLabel('Canvas name').fill('Independent canvas')
  await page.getByRole('dialog').getByRole('button', { name: 'Create canvas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Independent canvas' })).toBeVisible()
  await expect(page.locator('.kanban-column')).toHaveCount(6)
  await expect(page.locator('.kanban-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Team alignment', exact: true }).click()
  await expect(page.locator('.kanban-column')).toHaveCount(7)
  await expect(column(page, 'Backlog').locator('.kanban-card')).toHaveText('Keep this card')
  await column(page, 'Ready').getByLabel('Column actions for Ready').click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('group', { name: 'Column actions for Ready' }).getByRole('button', { name: 'Delete column', exact: true }).click()
  await expect(page.locator('.kanban-column')).toHaveCount(6)
})
