import { expect, test } from '@playwright/test'
import { addBoardCard, column, openBoard, openBoardCard, setStatus } from './support/board-fixtures'

test('moves cards by drag within and across columns, preserving stable IDs and reload order', async ({ page }) => {
  await openBoard(page)
  for (const title of ['Alpha', 'Beta', 'Gamma']) await addBoardCard(page, title)
  const ids = await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('lean-canvas:boards:v1')!))
    .flatMap((board) => (board as { cards: { id: string }[] }).cards.map((card) => card.id)).sort())
  const backlog = column(page, 'Backlog')
  await backlog.getByRole('button', { name: 'Gamma', exact: true }).dragTo(
    backlog.getByRole('button', { name: 'Alpha', exact: true }), { targetPosition: { x: 20, y: 3 } })
  await expect(backlog.locator('.kanban-card')).toHaveText(['Gamma', 'Alpha', 'Beta'])
  const gamma = backlog.getByRole('button', { name: 'Gamma', exact: true })
  const gammaBox = (await gamma.boundingBox())!
  await backlog.getByRole('button', { name: 'Beta', exact: true }).dragTo(gamma,
    { targetPosition: { x: 20, y: gammaBox.height - 3 } })
  await expect(backlog.locator('.kanban-card')).toHaveText(['Gamma', 'Beta', 'Alpha'])
  await backlog.getByRole('button', { name: 'Alpha', exact: true }).dragTo(column(page, 'Todo'))
  await expect(column(page, 'Todo').locator('.kanban-card')).toHaveText(['Alpha'])
  await page.reload()
  await page.getByRole('tab', { name: 'Tickets', exact: true }).click()
  await expect(backlog.locator('.kanban-card')).toHaveText(['Gamma', 'Beta'])
  await expect(column(page, 'Todo').locator('.kanban-card')).toHaveText(['Alpha'])
  expect(await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('lean-canvas:boards:v1')!))
    .flatMap((board) => (board as { cards: { id: string }[] }).cards.map((card) => card.id)).sort())).toEqual(ids)
})

test('mobile card details change status without dragging and persist after reload', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await openBoard(page)
  await addBoardCard(page, 'First')
  await openBoardCard(page, 'First')
  const modal = page.getByRole('dialog')
  await expect(modal.getByRole('combobox', { name: 'Story points' })).toHaveValue('')
  await expect(modal.getByRole('combobox', { name: 'Status', exact: true })).toHaveText('Backlog')
  await setStatus(page, 'In Progress')
  await expect(modal.getByText('Unsaved changes', { exact: true })).toBeVisible()
  await modal.getByLabel('Description').fill('Moved using the status selector.')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(column(page, 'Backlog').locator('.kanban-card')).toHaveCount(0)
  await expect(column(page, 'In Progress').locator('.kanban-card')).toHaveText(['First'])
  await page.reload()
  await openBoardCard(page, 'First')
  await expect(modal.getByRole('combobox', { name: 'Status', exact: true })).toHaveText('In Progress')
  await expect(modal.getByLabel('Description')).toHaveValue('Moved using the status selector.')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
})

test('status options include custom columns and cancelled changes do not move tickets', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 667 })
  await openBoard(page)
  await addBoardCard(page, 'Keep in backlog')
  await page.getByRole('button', { name: '+ Add another column' }).click()
  await page.getByLabel('Column title', { exact: true }).fill('Waiting for customer')
  await page.getByRole('button', { name: 'Add column', exact: true }).click()
  await openBoardCard(page, 'Keep in backlog')
  const modal = page.getByRole('dialog')
  const status = modal.getByRole('combobox', { name: 'Status', exact: true })
  await setStatus(page, 'Waiting for customer')
  page.once('dialog', (dialog) => dialog.accept())
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(column(page, 'Backlog').locator('.kanban-card')).toHaveText(['Keep in backlog'])
  await openBoardCard(page, 'Keep in backlog')
  await expect(status).toHaveText('Backlog')
  await setStatus(page, 'Waiting for customer')
  await modal.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(column(page, 'Waiting for customer').locator('.kanban-card')).toHaveText(['Keep in backlog'])
})
