import { expect, test } from '@playwright/test'
import { openSampleCanvas, uploadCanvas } from './support/canvas-fixtures'

test('dismissed drafts stay local when switching or creating canvases', async ({ page }) => {
  await openSampleCanvas(page)
  await uploadCanvas(page, { name: 'Second canvas' })
  const nav = page.getByRole('navigation', { name: 'Lean canvases' })
  await nav.getByRole('button', { name: 'Team alignment' }).click()
  const section = page.locator('.canvas-cell').first()
  await section.getByRole('button', { name: '＋ Add a card' }).click()
  await page.getByRole('textbox', { name: 'New card' }).fill('First canvas draft')
  await page.keyboard.press('Escape')
  await section.getByRole('button', { name: '＋ Add a card' }).click()
  await expect(page.getByRole('textbox', { name: 'New card' })).toHaveValue('First canvas draft')
  await nav.getByRole('button', { name: 'Team alignment' }).click()
  await section.getByRole('button', { name: '＋ Add a card' }).click()
  await expect(page.getByRole('textbox', { name: 'New card' })).toHaveValue('First canvas draft')
  await nav.getByRole('button', { name: 'Second canvas' }).click()
  await section.getByRole('button', { name: '＋ Add a card' }).click()
  await expect(page.getByRole('textbox', { name: 'New card' })).toHaveValue('')
  await page.getByRole('textbox', { name: 'New card' }).fill('Second canvas draft')
  await page.getByRole('button', { name: 'Add canvas', exact: true }).click()
  await page.getByRole('button', { name: 'New', exact: true }).click()
  await page.getByRole('textbox', { name: 'Canvas name' }).fill('Third canvas')
  await page.getByRole('button', { name: 'Create canvas', exact: true }).click()
  await section.getByRole('button', { name: '＋ Add a card' }).click()
  await expect(page.getByRole('textbox', { name: 'New card' })).toHaveValue('')
})

test('keyboard editor returns focus to its card after cancel and save', async ({ page }) => {
  await openSampleCanvas(page)
  const card = page.locator('.card-content').first()
  const original = await card.innerText()
  await card.press('Enter')
  const editor = page.getByRole('textbox', { name: 'Edit card' })
  await expect(editor).toBeFocused()
  await editor.fill('Discard this')
  await editor.press('Escape')
  await expect(card).toHaveText(original)
  await expect(card).toBeFocused()
  await card.press('Enter')
  await editor.fill('Saved heading\nSaved body')
  await editor.press('Control+Enter')
  await expect(card).toHaveText('Saved headingSaved body')
  await expect(card).toBeFocused()
})

test('keyboard composer returns focus to its section after save or dismissal', async ({ page }) => {
  await openSampleCanvas(page)
  const section = page.locator('.canvas-cell').first()
  const add = section.getByRole('button', { name: '＋ Add a card' })
  await add.press('Enter')
  await page.getByRole('textbox', { name: 'New card' }).fill('Keyboard creation')
  await page.keyboard.press('Enter')
  await expect(section.getByRole('button', { name: 'Keyboard creation', exact: true })).toBeVisible()
  await expect(add).toBeFocused()
  await page.keyboard.press('Enter')
  await page.getByRole('textbox', { name: 'New card' }).fill('Preserved draft')
  await page.keyboard.press('Escape')
  await expect(add).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox', { name: 'New card' })).toHaveValue('Preserved draft')
})
