import { expect, test } from '@playwright/test'
import { openSampleCanvas } from './support/canvas-fixtures'

test('dialog padding preserves the draft, Escape closes, and reopening starts empty', async ({ page }) => {
  await openSampleCanvas(page)
  const add = page.getByRole('button', { name: 'Add canvas', exact: true })
  await add.click()
  await page.getByRole('button', { name: 'New', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Create canvas' })
  const input = page.getByRole('textbox', { name: 'Canvas name' })
  await input.fill('Keep while clicking inside')
  await dialog.click({ position: { x: 5, y: 5 } })
  await expect(input).toHaveValue('Keep while clicking inside')
  await input.press('Escape')
  await expect(dialog).toHaveCount(0)
  await add.click()
  await page.getByRole('button', { name: 'New', exact: true }).click()
  await expect(input).toHaveValue('')
  await input.fill('  ')
  await page.getByRole('button', { name: 'Create canvas', exact: true }).click()
  await expect(dialog).toBeVisible()
  await page.mouse.click(2, 2)
  await expect(dialog).toHaveCount(0)
})

test('long mobile title editing leaves every toolbar control inside the header', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await openSampleCanvas(page)
  await page.getByRole('heading').getByRole('button').click()
  const input = page.getByRole('textbox', { name: 'Rename canvas' })
  await input.fill('A long title for customer research and planning')
  for (const button of await page.locator('.topbar button:visible').all()) {
    const box = await button.boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(320)
  }
  await input.press('Enter')
  await expect(page.getByRole('heading')).toHaveText('A long title for customer research and planning')
  await expect(page.getByRole('heading').getByRole('button')).toBeFocused()
  await page.keyboard.press('Enter')
  await input.fill('Discarded title')
  await input.press('Escape')
  await expect(page.getByRole('heading')).toHaveText('A long title for customer research and planning')
  await expect(page.getByRole('heading').getByRole('button')).toBeFocused()
})

test('add menu escapes clipping, dismisses outside, and restores keyboard focus', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await openSampleCanvas(page)
  const add = page.getByRole('button', { name: 'Add canvas', exact: true })
  await add.press('Enter')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'New', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(add).toBeFocused()
  await expect(add).toHaveAttribute('aria-expanded', 'false')
  await add.click()
  const popup = page.getByRole('group', { name: 'Add canvas options' })
  const box = await popup.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(320)
  await page.getByRole('heading').click()
  await expect(popup).not.toBeVisible()
})
