import { expect, test, type Page } from '@playwright/test'
import { addBoardCard, column, openBoard, openBoardCard, setStatus } from './support/board-fixtures'

async function addChild(page: Page, title: string) {
  const children = page.getByRole('region', { name: /^Subtasks/ })
  await children.getByRole('button', { name: 'Add ticket', exact: true }).click()
  await children.getByLabel('Ticket title').fill(title)
  await children.getByLabel('Ticket title').press('Enter')
  await expect(children.getByRole('button', { name: new RegExp(title) })).toBeVisible()
}

test('nested lists and boards persist, scope movement, and preserve active descendants', async ({ page }) => {
  await openBoard(page)
  await addBoardCard(page, 'Login')
  await addBoardCard(page, 'Unrelated project ticket')
  await openBoardCard(page, 'Login')
  const parentUrl = page.url()
  await addChild(page, 'Email login')
  await addChild(page, 'Google login')
  await expect(page.getByRole('button', { name: 'Delete card', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Email login Backlog', exact: true }).click()
  await addChild(page, 'Password reset')
  const childUrl = page.url()
  await page.getByRole('button', { name: 'Password reset Backlog', exact: true }).click()
  await setStatus(page, 'Todo')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).toHaveURL(`${childUrl}/board`)
  await expect(page.locator('.kanban-card')).toHaveCount(1)
  await expect(column(page, 'Todo').getByRole('button', { name: 'Password reset', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.kanban-card')).toHaveCount(1)
  await page.getByRole('navigation', { name: 'Ticket hierarchy' }).getByRole('button', { name: 'Login', exact: true }).click()
  await expect(page).toHaveURL(`${parentUrl}/board`)
  await expect(page.locator('.kanban-card')).toHaveCount(2)
  await column(page, 'Backlog').getByRole('button', { name: 'Google login', exact: true }).dragTo(column(page, 'Todo'))
  await expect(column(page, 'Todo').getByRole('button', { name: 'Google login', exact: true })).toBeVisible()
  await openBoardCard(page, 'Google login')
  await setStatus(page, 'Done')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('navigation', { name: 'Ticket hierarchy' }).getByRole('button', { name: 'Login', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Subtasks 1/2 done' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Status', exact: true })).toHaveText('Backlog')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.locator('.kanban-card')).toHaveCount(2)
  await expect(page.locator('.kanban-card').filter({ hasText: 'Email login' })).toHaveCount(0)
  await page.goto('/tickets')
  await expect(page.getByRole('button', { name: 'Password reset, Todo', exact: true })).toBeVisible()
  await expect(page.locator('.ticket-parent-path')).toHaveText('Login / Email login')
})

test('protects parent fields and child drafts, supports back and missing-parent recovery', async ({ page }) => {
  await openBoard(page)
  await addBoardCard(page, 'Parent')
  await openBoardCard(page, 'Parent')
  await addChild(page, 'Child')
  const parentUrl = page.url()
  await page.getByLabel('Description', { exact: true }).fill('Unsaved parent description')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Open board', exact: true }).click()
  await expect(page).toHaveURL(parentUrl)
  let confirms = 0
  const accept = async (dialog: import('@playwright/test').Dialog) => { confirms++; await dialog.accept() }
  page.on('dialog', accept)
  await page.getByRole('button', { name: 'Open board', exact: true }).click()
  await expect(page).toHaveURL(`${parentUrl}/board`)
  expect(confirms).toBe(1)
  page.off('dialog', accept)
  await page.goBack()
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Parent')
  await page.getByRole('region', { name: /^Subtasks/ }).getByRole('button', { name: 'Add ticket', exact: true }).click()
  await page.getByLabel('Ticket title').fill('Unsubmitted child')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByLabel('Ticket title')).toHaveValue('Unsubmitted child')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.goto(`${parentUrl.replace(/\/[^/]+$/, '/missing')}/board`)
  await expect(page.getByRole('alert')).toContainText('parent ticket is unavailable')
  await expect(page.locator('.kanban-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Project board', exact: true }).click()
  await expect(page.locator('.kanban-card')).toHaveCount(1)
})
