import { expect, test } from '@playwright/test'
import { openSampleCanvas } from './support/canvas-fixtures'

test('desktop notes expand, restore, and follow the available workspace', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await openSampleCanvas(page)
  await page.getByRole('button', { name: 'Notepad', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Notepad' })
  const notes = panel.getByRole('textbox', { name: 'Canvas notes' })
  await notes.fill('Customer research\n\nInterview five teams about their workflow.\n\nCapture blockers, decisions, and next steps here.')
  const handle = panel.getByRole('separator', { name: 'Resize notepad' })
  await handle.focus()
  for (let i = 0; i < 20; i++) await handle.press('ArrowLeft')
  await expect(handle).toHaveAttribute('aria-valuenow', '720')
  await expect.poll(() => panel.evaluate((element) => Math.round(element.getBoundingClientRect().width))).toBe(720)
  await expect(page.getByRole('status')).toBeEmpty()
  await page.mouse.move(0, 0)
  await page.screenshot({ path: 'docs/pr-proofs/desktop-notes/desktop-resized.png' })
  await panel.getByRole('button', { name: 'Expand notepad' }).click()
  const availableWidth = () => page.locator('.workspace-content').evaluate((element) => element.clientWidth)
  const panelWidth = () => panel.evaluate((element) => Math.round(element.getBoundingClientRect().width))
  await expect.poll(panelWidth).toBe(await availableWidth())
  await expect(page.getByRole('main', { name: 'Lean canvas' })).not.toBeVisible()
  const updatedNotes = 'Customer research\n\nInterview five teams about their workflow.\n\nCapture blockers, decisions, and next steps here.\n\nNext interview: Tuesday.'
  await notes.fill(updatedNotes)
  await expect(panel.locator('header p')).toHaveText('Saved')
  await page.screenshot({ path: 'docs/pr-proofs/desktop-notes/desktop-expanded.png' })
  await page.getByRole('button', { name: 'Expand sidebar' }).click()
  await expect.poll(panelWidth).toBe(1192)
  await expect(page.getByRole('navigation', { name: 'Workspace navigation' })).toBeVisible()
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect.poll(panelWidth).toBe(776)
  await page.getByRole('button', { name: 'Collapse sidebar' }).click()
  await expect.poll(panelWidth).toBe(1024)
  await panel.getByRole('button', { name: 'Restore notepad width' }).click()
  await expect.poll(panelWidth).toBe(720)
  await expect(notes).toContainText('Next interview: Tuesday.')
  await expect(page.getByRole('main', { name: 'Lean canvas' })).toBeVisible()
  await handle.focus()
  await handle.press('End')
  await expect.poll(panelWidth).toBe(1024)
  await handle.press('Home')
  await expect.poll(panelWidth).toBe(260)
  const bounds = await handle.boundingBox()
  await page.mouse.move(bounds!.x + bounds!.width - 1, bounds!.y + 80)
  await page.mouse.down()
  await page.mouse.move(10, bounds!.y + 80)
  await page.mouse.up()
  await expect.poll(panelWidth).toBeGreaterThan(640)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: 'Notepad', exact: true }).click()
  await expect(page.locator('#canvas-notepad')).toHaveAttribute('aria-hidden', 'true')
  await expect(page.getByRole('main', { name: 'Lean canvas' })).toBeVisible()
})

test('mobile notes still fill the screen without a redundant expand button', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openSampleCanvas(page)
  await page.getByRole('button', { name: 'More actions', exact: true }).click()
  await page.getByRole('button', { name: 'Notepad', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Notepad' })
  await expect(panel.getByRole('button', { name: 'Expand notepad' })).not.toBeVisible()
  await expect(panel.getByRole('separator')).not.toBeVisible()
  await expect.poll(() => panel.evaluate((element) => {
    const { left, right, top, bottom } = element.getBoundingClientRect()
    return { left, right, top, bottom }
  })).toEqual({ left: 0, right: 390, top: 48, bottom: 844 })
  await panel.getByRole('textbox', { name: 'Canvas notes' }).fill('Customer research\n\nInterview five teams about their workflow.\n\nCapture blockers, decisions, and next steps here.')
  await expect(page.getByRole('status')).toBeEmpty()
  await page.mouse.move(0, 0)
  await page.screenshot({ path: 'docs/pr-proofs/desktop-notes/mobile.png' })
})
