import { expect, test } from '@playwright/test'
import { loadSamples } from './support/canvas-fixtures'
import { expectHeaderLayout } from './support/header-layout'

test('About saves per project, survives reloads, and follows browser history', async ({ page }) => {
  await loadSamples(page)
  const canvasUrl = page.url()
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  await expect(page).toHaveURL(`${canvasUrl}/about`)
  const details = page.getByRole('textbox', { name: 'Project details' })
  await expect(details).toHaveValue('')
  const text = 'Help travelers find a place to stay.\n\nGoal: validate demand with three hosts.\nhttps://example.com'
  await details.fill(text)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: 'About' }).getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(details).toHaveValue(text)
  await page.getByRole('button', { name: 'Notepad', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Canvas notes' })).toHaveValue('')
  await page.getByRole('button', { name: 'Notepad', exact: true }).click()
  const projects = page.getByRole('navigation', { name: 'Workspace navigation' }).getByRole('button')
  await page.getByRole('button', { name: 'Expand sidebar' }).click()
  await projects.nth(1).click()
  await expect(page.getByRole('tab', { name: 'About', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(details).toHaveValue('')
  await details.fill('A different project overview')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: 'About' }).getByRole('status')).toContainText('All changes saved')
  await page.goBack()
  await expect(details).toHaveValue(text)
  await page.getByRole('tab', { name: 'Tickets', exact: true }).click()
  await expect(page).toHaveURL(`${canvasUrl}/ticket`)
  await page.goBack()
  await expect(details).toHaveValue(text)
  await details.fill('')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: 'About' }).getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(details).toHaveValue('')
})

test('all three tabs support arrow wraparound and Home/End', async ({ page }) => {
  await loadSamples(page)
  const tickets = page.getByRole('tab', { name: 'Tickets', exact: true })
  const about = page.getByRole('tab', { name: 'About', exact: true })
  await tickets.click()
  await page.keyboard.press('ArrowLeft')
  await expect(about).toBeFocused()
  await expect(page.getByRole('tabpanel', { name: 'About' })).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(tickets).toBeFocused()
  await page.keyboard.press('End')
  await expect(about).toBeFocused()
  await page.keyboard.press('Home')
  await expect(tickets).toBeFocused()
})

for (const width of [320, 375, 768, 1440]) {
  test(`About and header fit at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 800 })
    await loadSamples(page)
    await page.getByRole('tab', { name: 'About', exact: true }).click()
    await expectHeaderLayout(page, width)
    const details = page.getByRole('textbox', { name: 'Project details' })
    await expect(details).toBeVisible()
    const bounds = await details.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
  })
}
