import { expect, test } from '@playwright/test'
import { loadSamples } from './support/canvas-fixtures'

test('on phones the section list collapses and swaps with the editor', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 760 })
  await loadSamples(page)
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'About' })
  const toggle = panel.getByRole('button', { name: /^Sections/ })
  const sections = panel.getByRole('tablist', { name: 'About sections' })
  const overview = panel.getByRole('textbox', { name: 'Project details' })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(sections).toBeHidden()
  await expect(overview).toBeVisible()
  await panel.getByRole('button', { name: 'Add tab' }).click()
  await expect(overview).toBeHidden()
  await panel.getByRole('textbox', { name: 'Tab name' }).fill('Goals')
  await page.keyboard.press('Enter')
  await expect(sections).toBeHidden()
  await expect(toggle).toBeFocused()
  await expect(toggle).toContainText('Goals')
  await expect(panel.getByRole('textbox', { name: 'Goals' })).toBeVisible()
  for (const action of ['Rename tab', 'Move tab up', 'Move tab down', 'Delete tab']) {
    const bounds = await panel.getByRole('button', { name: action }).boundingBox()
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(375)
    expect(bounds!.height).toBeGreaterThanOrEqual(44)
  }
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(sections).toBeVisible()
  await expect(panel.getByRole('textbox', { name: 'Goals' })).toBeHidden()
  await sections.getByRole('tab', { name: 'Overview' }).click()
  await expect(sections).toBeHidden()
  await expect(overview).toBeVisible()
  await expect(toggle).toContainText('Overview')
  await expect(toggle).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
})

test('phone keyboard navigation keeps the list open until a section is activated', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 760 })
  await loadSamples(page)
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'About' })
  const toggle = panel.getByRole('button', { name: /^Sections/ })
  const sections = panel.getByRole('tablist', { name: 'About sections' })
  for (const title of ['Goals', 'Links']) {
    await panel.getByRole('button', { name: 'Add tab' }).click()
    await panel.getByRole('textbox', { name: 'Tab name' }).fill(title)
    await page.keyboard.press('Enter')
    await expect(toggle).toBeFocused()
  }
  await toggle.press('Enter')
  await sections.getByRole('tab', { name: 'Links' }).focus()
  for (const [key, title] of [['ArrowDown', 'Overview'], ['ArrowDown', 'Goals'], ['End', 'Links'], ['Home', 'Overview'], ['ArrowUp', 'Links']]) {
    await page.keyboard.press(key)
    await expect(sections).toBeVisible()
    await expect(sections.getByRole('tab', { name: title })).toBeFocused()
    await expect(sections.getByRole('tab', { name: title })).toHaveAttribute('aria-selected', 'true')
  }
  await page.keyboard.press('Enter')
  await expect(sections).toBeHidden()
  await expect(toggle).toBeFocused()
  await expect(panel.getByRole('textbox', { name: 'Links' })).toBeVisible()
  await toggle.press('Space')
  await sections.getByRole('tab', { name: 'Goals' }).focus()
  await page.keyboard.press('Space')
  await expect(sections).toBeHidden()
  await expect(toggle).toBeFocused()
  await expect(panel.getByRole('textbox', { name: 'Goals' })).toBeVisible()
  await panel.getByRole('button', { name: 'Rename tab' }).click()
  await panel.getByRole('textbox', { name: 'Tab name' }).fill('Cancel this')
  await page.keyboard.press('Escape')
  await expect(sections).toBeHidden()
  await expect(toggle).toBeFocused()
  await expect(toggle).toContainText('Goals')
})

test('blurring a phone rename does not swallow a click on another section', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 760 })
  await loadSamples(page)
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'About' })
  const sections = panel.getByRole('tablist', { name: 'About sections' })
  const toggle = panel.getByRole('button', { name: /^Sections/ })
  await panel.getByRole('button', { name: 'Add tab' }).click()
  await panel.getByRole('textbox', { name: 'Tab name' }).fill('Goals')
  await sections.getByRole('tab', { name: 'Overview' }).click()
  await expect(sections).toBeHidden()
  await expect(toggle).toContainText('Overview')
  await expect(toggle).toBeFocused()
  await toggle.click()
  await expect(sections.getByRole('tab', { name: 'Goals' })).toBeVisible()
})
