import { expect, test } from '@playwright/test'
import { loadSamples } from './support/canvas-fixtures'

test('About tabs can be added, renamed, deleted, and survive reloads', async ({ page }) => {
  await loadSamples(page)
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'About' })
  const sections = panel.getByRole('tablist', { name: 'About sections' })
  await expect(sections.getByRole('tab', { name: 'Overview' })).toHaveAttribute('aria-selected', 'true')
  await panel.getByRole('button', { name: 'Add tab' }).click()
  const name = panel.getByRole('textbox', { name: 'Tab name' })
  await expect(name).toBeFocused()
  await name.fill('Goals')
  await panel.getByRole('textbox', { name: 'Goals' }).fill('Validate demand with three hosts.')
  await sections.getByRole('tab', { name: 'Overview' }).click()
  await panel.getByRole('textbox', { name: 'Project details' }).fill('Overview copy')
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await sections.getByRole('tab', { name: 'Goals' }).click()
  await expect(panel.getByRole('textbox', { name: 'Goals' })).toHaveText('Validate demand with three hosts.')
  await page.keyboard.press('Home')
  await expect(sections.getByRole('tab', { name: 'Overview' })).toBeFocused()
  await expect(panel.getByRole('textbox', { name: 'Project details' })).toHaveText('Overview copy')
  await sections.getByRole('tab', { name: 'Goals' }).click()
  await name.fill('')
  await expect(panel.getByRole('status')).toContainText('Every tab needs a name.')
  await expect(panel.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
  await panel.getByRole('button', { name: 'Delete tab' }).click()
  await expect(sections.getByRole('tab')).toHaveCount(1)
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(sections.getByRole('tab')).toHaveCount(1)
})

test('About tabs are vertical and can be reordered by drag, keyboard, and buttons', async ({ page }) => {
  await loadSamples(page)
  await page.getByRole('tab', { name: 'About', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'About' })
  const sections = panel.getByRole('tablist', { name: 'About sections' })
  await expect(sections).toHaveAttribute('aria-orientation', 'vertical')
  for (const title of ['Goals', 'Links', 'Risks']) {
    await panel.getByRole('button', { name: 'Add tab' }).click()
    await panel.getByRole('textbox', { name: 'Tab name' }).fill(title)
  }
  const order = () => sections.getByRole('tab').allTextContents()
  await expect.poll(order).toEqual(['Overview', 'Goals', 'Links', 'Risks'])
  await sections.getByRole('tab', { name: 'Risks' }).dragTo(sections.getByRole('tab', { name: 'Goals' }), { targetPosition: { x: 20, y: 2 } })
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Goals', 'Links'])
  await sections.getByRole('tab', { name: 'Goals' }).click()
  await page.keyboard.press('Alt+ArrowDown')
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Links', 'Goals'])
  await expect(sections.getByRole('tab', { name: 'Goals' })).toBeFocused()
  await page.keyboard.press('Alt+ArrowDown')
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Links', 'Goals'])
  await expect(panel.getByRole('button', { name: 'Move tab down' })).toBeDisabled()
  await panel.getByRole('button', { name: 'Move tab up' }).click()
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Goals', 'Links'])
  await sections.getByRole('tab', { name: 'Overview' }).focus()
  await page.keyboard.press('Alt+ArrowDown')
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Goals', 'Links'])
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect.poll(order).toEqual(['Overview', 'Risks', 'Goals', 'Links'])
})
