import { expect, test } from '@playwright/test'
import { loadSamples } from './support/canvas-fixtures'

test('root defaults to Tickets, preserves Canvas deep links, and does not add a history entry', async ({ page }) => {
  await loadSamples(page)
  const canvasUrl = page.url()
  await page.goto('/tickets')
  await page.goto('/')
  await expect(page).toHaveURL(`${canvasUrl}/ticket`)
  await expect(page.getByRole('tabpanel', { name: 'Tickets' })).toBeVisible()
  await expect(page.getByRole('tab')).toHaveText(['Tickets', 'Canvas', 'About'])
  await page.goBack()
  await expect(page).toHaveURL(/\/tickets$/)
  await page.goForward()
  await expect(page).toHaveURL(`${canvasUrl}/ticket`)
  await page.getByRole('tab', { name: 'Canvas', exact: true }).click()
  await expect(page).toHaveURL(canvasUrl)
  await page.reload()
  await expect(page.getByRole('tabpanel', { name: 'Canvas' })).toBeVisible()
  await page.goto(canvasUrl)
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).toHaveAttribute('aria-selected', 'true')
})

test('the first created project opens Tickets, with Home/End matching visual order', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Add canvas' }).click()
  await page.getByRole('button', { name: 'New', exact: true }).click()
  await page.getByRole('textbox', { name: 'Canvas name' }).fill('New project')
  await page.getByRole('button', { name: 'Create canvas', exact: true }).click()
  await expect(page).toHaveURL(/\/project\/[^/]+\/ticket$/)
  const tickets = page.getByRole('tab', { name: 'Tickets', exact: true })
  const about = page.getByRole('tab', { name: 'About', exact: true })
  await expect(tickets).toHaveAttribute('aria-selected', 'true')
  await tickets.focus()
  await page.keyboard.press('End')
  await expect(about).toBeFocused()
  await expect(about).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Home')
  await expect(tickets).toBeFocused()
  await expect(tickets).toHaveAttribute('aria-selected', 'true')
})
