import { expect, test } from '@playwright/test'
import { answerHistoryNavigation } from './support/history-navigation'
import { addBoardCard, openBoard, openBoardCard } from './support/board-fixtures'
import { loadSamples } from './support/canvas-fixtures'

test('selecting projects and views updates history, including Back/Forward and refresh', async ({ page }) => {
  await loadSamples(page)
  const first = new URL(page.url()).pathname
  expect(first).toMatch(/^\/project\/[^/]+$/)
  await page.getByRole('tab', { name: 'Board', exact: true }).click()
  await expect(page).toHaveURL(`${first}/ticket`)
  await page.getByRole('button', { name: 'Facebook', exact: true }).click()
  const second = page.url()
  expect(second).not.toContain(first)
  await page.goBack()
  await expect(page).toHaveURL(`${first}/ticket`)
  await expect(page.getByRole('tab', { name: 'Board', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.goBack()
  await expect(page).toHaveURL(first)
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.goForward()
  await page.goForward()
  await expect(page).toHaveURL(second)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Facebook — 2004' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Board', exact: true })).toHaveAttribute('aria-selected', 'true')
})

test('ticket URL loads directly, survives refresh, closes to parent, and restores with history', async ({ page }) => {
  await openBoard(page)
  const parent = page.url()
  await addBoardCard(page, 'Linked ticket')
  await openBoardCard(page, 'Linked ticket')
  const ticket = page.url()
  expect(ticket).toMatch(/\/ticket\/[^/]+$/)
  await page.reload()
  await expect(page.getByRole('dialog', { name: 'Card details' })).toBeVisible()
  await page.goto(ticket)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page).toHaveURL(parent)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goBack()
  await expect(page).toHaveURL(ticket)
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.goForward()
  await expect(page).toHaveURL(parent)
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('cancelled Back preserves ticket drafts and history; confirmed Back and Forward still work', async ({ page }) => {
  await openBoard(page)
  const parent = page.url()
  await addBoardCard(page, 'Guarded ticket')
  await openBoardCard(page, 'Guarded ticket')
  const ticket = page.url()
  await page.getByLabel('Description').fill('Do not lose me')
  await page.getByLabel('New comment').fill('Draft comment')
  for (let attempt = 0; attempt < 2; attempt++) {
    await answerHistoryNavigation(page, -1, false)
    await expect(page).toHaveURL(ticket)
    await expect(page.getByLabel('Description')).toHaveValue('Do not lose me')
    await expect(page.getByLabel('New comment')).toHaveValue('Draft comment')
  }
  await answerHistoryNavigation(page, -1, true)
  await expect(page).toHaveURL(parent)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goForward()
  await expect(page).toHaveURL(ticket)
  await expect(page.getByLabel('Description')).toHaveValue('')
})

test('cancelled Forward preserves Board composer and confirmed Forward opens ticket', async ({ page }) => {
  await openBoard(page)
  const parent = page.url()
  await addBoardCard(page, 'Forward ticket')
  await openBoardCard(page, 'Forward ticket')
  const ticket = page.url()
  await page.goBack()
  await page.getByRole('button', { name: '+ Add a card', exact: true }).first().click()
  await page.getByRole('textbox', { name: 'Card title', exact: true }).fill('Keep composer')
  await answerHistoryNavigation(page, 1, false)
  await expect(page).toHaveURL(parent)
  await expect(page.getByRole('textbox', { name: 'Card title', exact: true })).toHaveValue('Keep composer')
  await answerHistoryNavigation(page, 1, true)
  await expect(page).toHaveURL(ticket)
  await expect(page.getByRole('dialog')).toBeVisible()
})
