import { chromium, expect } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const base = process.env.STAGING_BASE_URL ?? 'http://127.0.0.1:4174'
const proof = process.env.STAGING_PROOF_DIR ?? '/workspace/scratch/lean-staging-proof/local'
await mkdir(proof, { recursive: true })
const axe = await readFile('node_modules/axe-core/axe.min.js', 'utf8')
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/usr/bin/chromium', args: ['--no-sandbox'] })
const results = []
try {
  for (const width of [1440, 390, 320]) {
    const context = await browser.newContext({ viewport: { width, height: width > 760 ? 900 : 844 } })
    const page = await context.newPage()
    const errors = [], origins = new Set()
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('request', (request) => origins.add(new URL(request.url()).origin))
    const response = await page.goto(base)
    expect(response.status()).toBe(200)
    expect(response.headers()['content-security-policy']).toContain("connect-src 'self'")
    expect(response.headers()['x-robots-tag']).toContain('noindex')
    await expect(page.getByRole('tab', { name: 'Tickets', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.locator('.kanban-column')).toHaveCount(6)
    await expect(page.getByRole('complementary', { name: 'Staging demo information' })).toBeVisible()
    expect(await page.locator('body').evaluate((el) => el.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: path.join(proof, `tickets-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Draft the pilot plan', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Card details' })
    await expect(dialog).toBeVisible()
    const ticketPath = new URL(page.url()).pathname
    expect(ticketPath).toBe('/project/demo-pilot/ticket/plan')
    await dialog.getByLabel('Description', { exact: true }).fill('Saved in this browser only.')
    await dialog.getByLabel('New comment', { exact: true }).fill('A synthetic staging comment.')
    await dialog.getByRole('button', { name: 'Add comment', exact: true }).click()
    await expect(dialog.getByText('A synthetic staging comment.', { exact: true })).toBeVisible()
    await dialog.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await page.goto(base + ticketPath)
    await expect(dialog.getByLabel('Description', { exact: true })).toHaveValue('Saved in this browser only.')
    await expect(dialog.getByText('A synthetic staging comment.', { exact: true })).toBeVisible()
    await page.evaluate(axe)
    const cardAudit = await page.evaluate(async () => (await window.axe.run()).violations.map(({ id, impact }) => ({ id, impact })))
    expect(cardAudit).toEqual([])
    await page.screenshot({ path: path.join(proof, `card-${width}.png`), fullPage: true })
    await dialog.getByRole('button', { name: 'Close dialog', exact: true }).click()
    await page.getByRole('tab', { name: 'Canvas', exact: true }).click()
    await expect(page.locator('.canvas-cell')).toHaveCount(12)
    await page.screenshot({ path: path.join(proof, `canvas-${width}.png`), fullPage: true })
    await page.evaluate(axe)
    const canvasAudit = await page.evaluate(async () => (await window.axe.run()).violations.map(({ id, impact }) => ({ id, impact })))
    expect(canvasAudit).toEqual([])
    await page.getByRole('tab', { name: 'About', exact: true }).click()
    const details = page.getByRole('textbox', { name: 'Project details', exact: true })
    await expect(details).toBeVisible()
    await details.fill('Synthetic staging edit')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('tabpanel', { name: 'About' }).getByRole('status')).toContainText('All changes saved')
    await page.reload()
    await expect(details).toHaveText('Synthetic staging edit')
    if (width <= 760) await page.getByRole('button', { name: 'More actions', exact: true }).click()
    await page.getByRole('button', { name: 'Notepad', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Canvas notes', exact: true })).toBeVisible()
    await page.goto(base + '/tickets')
    await expect(page.getByRole('button', { name: 'Open board for Launch pilot', exact: true })).toBeVisible()
    await page.screenshot({ path: path.join(proof, `all-tickets-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
    await expect(page.locator('.kanban-column')).toHaveCount(6)
    await page.goto(base + ticketPath)
    await expect(dialog.getByLabel('Description', { exact: true })).toHaveValue('')
    await expect(dialog.getByText('A synthetic staging comment.', { exact: true })).toHaveCount(0)
    expect(errors).toEqual([])
    const allowed = [new URL(base).origin, 'https://fonts.googleapis.com', 'https://fonts.gstatic.com']
    expect([...origins].filter((origin) => !allowed.includes(origin))).toEqual([])
    expect(await page.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length)).toBe(0)
    results.push({ width, status: 'passed', cardAudit, canvasAudit, requestOrigins: [...origins] })
    await context.close()
  }
  await writeFile(path.join(proof, 'browser-results.json'), JSON.stringify({ base, results }, null, 2))
  console.log(JSON.stringify({ base, viewports: results.map(({ width }) => width), status: 'passed', proof }))
} finally { await browser.close() }
/* global process, URL, innerWidth, window, navigator, console */
