import { expect,test } from '@playwright/test'
test('real Better Auth cookie session, API persistence, nested board, and cross-tab refresh',async({page,context})=>{
  await page.goto('/project/project/ticket')
  await page.getByLabel('Email',{exact:true}).fill('alice@example.com')
  await page.getByLabel('Password',{exact:true}).fill('correct-password')
  await page.getByRole('button',{name:'Sign in with email',exact:true}).click()
  await expect(page.getByRole('button',{name:'PostgreSQL migration',exact:true})).toBeVisible()
  const second=await context.newPage()
  await second.goto('/project/project/ticket')
  await page.getByRole('button',{name:'PostgreSQL migration',exact:true}).click()
  await expect(page.getByRole('button',{name:'Verify account isolation Review',exact:true})).toBeVisible()
  await page.getByLabel('Title',{exact:true}).fill('PostgreSQL verified')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(second.getByRole('button',{name:'PostgreSQL verified',exact:true})).toBeVisible({timeout:10000})
  await page.reload()
  await expect(page.getByRole('button',{name:'PostgreSQL verified',exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/postgres-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'PostgreSQL verified',exact:true}).click()
  await page.screenshot({path:'test-results/postgres-mobile.png',fullPage:true})
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('PostgreSQL verified')
})
